-- Demo seed data for the MVP
-- Run in Supabase SQL editor after creating the table.

insert into public.businesses (
  company_name,
  owner_name,
  country,
  city,
  industry,
  sub_industry,
  description,
  phone,
  address,
  other_locations,
  locations_description,
  offerings,
  offerings_description,
  website,
  email,
  approval_status
) values
(
  'Skopje Street Bakery',
  'Elena S.',
  'Germany',
  'Berlin',
  'Food & Beverage',
  'Bakery',
  'Traditional Macedonian pastries, breads, and celebratory cakes for the diaspora community.',
  '+49 30 123 456',
  'Prenzlauer Allee 12',
  'Munich; Hamburg',
  'Delivery across Germany (selected cities).',
  'Burek, kifli, cakes, catering',
  'Custom orders for events, corporate catering, and weekly delivery boxes.',
  'https://example.com/bakery',
  'demo1@diaspora.example',
  'approved'
),
(
  'Ohrid Lake Travel Co.',
  'Dragan P.',
  'United States',
  'Chicago',
  'Hospitality',
  'Travel & Tours',
  'Diaspora-focused travel planning with curated Balkan itineraries and group trips.',
  '+1 (312) 555-0142',
  '210 W Lake St',
  null,
  'Serving clients across North America.',
  'Flight + hotel planning, guided tours, group travel',
  'Personalized planning with flexible budgets and bilingual support.',
  'https://example.com/travel',
  'demo2@diaspora.example',
  'approved'
),
(
  'Vardar IT Studio',
  'Marija K.',
  'Switzerland',
  'Zurich',
  'Technology',
  'Web Development',
  'Small product studio building fast, clean websites and internal tools for SMEs.',
  '+41 44 555 0199',
  null,
  'Remote',
  'Remote-first, available worldwide.',
  'Web apps, landing pages, integrations',
  'Next.js builds, Supabase backends, and quick MVP delivery.',
  'https://example.com/it',
  'demo3@diaspora.example',
  'approved'
),
(
  'Diaspora Accounting & Tax',
  'Nikola R.',
  'Australia',
  'Melbourne',
  'Professional Services',
  'Accounting',
  'Bookkeeping, payroll, and tax support for small businesses and contractors.',
  '+61 3 5550 0123',
  'Collins St 88',
  null,
  null,
  'Bookkeeping, BAS/GST, payroll',
  'Monthly packages and one-off advisory sessions.',
  'https://example.com/accounting',
  'demo4@diaspora.example',
  'approved'
),
(
  'Bitola Builders',
  'Stefan M.',
  'Canada',
  'Toronto',
  'Construction',
  'Renovations',
  'Residential renovations, kitchens, bathrooms, and small commercial fit-outs.',
  '+1 (647) 555-0107',
  null,
  'Mississauga; Vaughan',
  'Greater Toronto Area.',
  'Renovations, tiling, drywall, painting',
  'Free estimates and transparent timelines.',
  'https://example.com/builders',
  'demo5@diaspora.example',
  'approved'
),
(
  'Tetovo Fitness Club',
  'Ana T.',
  'Austria',
  'Vienna',
  'Healthcare',
  'Fitness',
  'Community gym with personal training and small-group classes.',
  '+43 1 555 0133',
  'Landstrasse 41',
  null,
  null,
  'Personal training, group classes, nutrition coaching',
  'Beginner-friendly programs and flexible memberships.',
  'https://example.com/fitness',
  'demo6@diaspora.example',
  'approved'
),
(
  'Sun of Macedonia Imports',
  'Bojan L.',
  'Netherlands',
  'Rotterdam',
  'Logistics',
  'Import/Export',
  'Importing Balkan specialty goods and distributing to European retailers.',
  '+31 10 555 0188',
  null,
  null,
  'EU-wide delivery.',
  'Import, warehousing, last-mile distribution',
  'Cold-chain options available on request.',
  'https://example.com/imports',
  'demo7@diaspora.example',
  'approved'
),
(
  'Krushevo Crafts',
  'Ivana J.',
  'United Kingdom',
  'London',
  'Arts & Culture',
  'Handmade Goods',
  'Handmade crafts inspired by Macedonian folk motifs and modern design.',
  null,
  null,
  'Online store',
  'Ships worldwide.',
  'Decor, gifts, custom pieces',
  'Small-batch releases and custom commissions.',
  'https://example.com/crafts',
  'demo8@diaspora.example',
  'approved'
),
(
  'Pelister Real Estate',
  'Goran V.',
  'Italy',
  'Milan',
  'Real Estate',
  'Property Management',
  'Helping diaspora clients buy, rent, and manage properties with confidence.',
  '+39 02 555 0101',
  null,
  null,
  null,
  'Rentals, sales support, property management',
  'Bilingual coordination and trusted local partners.',
  'https://example.com/realestate',
  'demo9@diaspora.example',
  'approved'
),
(
  'Strumica Retail & Deli',
  'Petar D.',
  'France',
  'Paris',
  'Retail',
  'Deli',
  'Balkan groceries, deli counter, and weekly fresh imports with Macedonian favorites.',
  '+33 1 55 55 01 55',
  'Rue du Commerce 19',
  null,
  null,
  'Groceries, deli, gift baskets',
  'Corporate gifts and seasonal baskets available.',
  'https://example.com/deli',
  'demo10@diaspora.example',
  'approved'
);
